# Generated by Django 2.0.4 on 2018-04-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foosball', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gameprofileentry',
            name='first_in',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='scores',
        ),
        migrations.DeleteModel(
            name='ScoreEntry',
        ),
    ]
